# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

name: CI

on: [push, pull_request]

# Cancel previous workflows if they are the same workflow on same ref (branch/tags)
# with the same event (push/pull_request) even they are in progress.
# This setting will help reduce the number of duplicated workflows.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event_name }}
  cancel-in-progress: true

jobs:
  license:
    name: Check license header
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: apache/skywalking-eyes/header@v0.4.0
        with:
          config: tools/ci/licenserc.yml

  lint:
    name: Lint and check code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code Base
        uses: actions/checkout@v3
      - name: Install Check Tools
        run: |
          sudo apt update
          sudo apt install -y cppcheck
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19.x
      - name: Setup dependencies
        run: pip install cpplint==1.5.0
      - name: Lint and check code
        run: |
          ./x.py check cpplint
          ./x.py check cppcheck
          ./x.py check golangci-lint

  build-and-test:
    name: Build and test
    needs: [license, lint]
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Darwin Clang
            os: macos-11
            compiler: auto
            with_openssl: -DENABLE_OPENSSL=ON
          - name: Darwin Clang without Jemalloc
            os: macos-11
            compiler: auto
            without_jemalloc: -DDISABLE_JEMALLOC=ON
            with_openssl: -DENABLE_OPENSSL=ON
          - name: Ubuntu GCC
            os: ubuntu-18.04
            compiler: gcc
            with_openssl: -DENABLE_OPENSSL=ON
          - name: Ubuntu Clang
            os: ubuntu-18.04
            compiler: clang
            with_openssl: -DENABLE_OPENSSL=ON
          - name: Ubuntu GCC ASan
            os: ubuntu-18.04
            without_jemalloc: -DDISABLE_JEMALLOC=ON
            with_sanitizer: -DENABLE_ASAN=ON
            with_openssl: -DENABLE_OPENSSL=ON
            compiler: gcc
          - name: Ubuntu GCC TSan
            os: ubuntu-18.04
            without_jemalloc: -DDISABLE_JEMALLOC=ON
            with_openssl: -DENABLE_OPENSSL=ON
            with_sanitizer: -DENABLE_TSAN=ON
            compiler: gcc
            runtime_env_vars: TSAN_OPTIONS="suppressions=$(realpath ./tests/tsan-suppressions)"
          - name: Ubuntu Clang ASan
            os: ubuntu-18.04
            with_sanitizer: -DENABLE_ASAN=ON
            without_jemalloc: -DDISABLE_JEMALLOC=ON
            with_openssl: -DENABLE_OPENSSL=ON
            compiler: clang
          - name: Ubuntu Clang TSan
            os: ubuntu-18.04
            with_sanitizer: -DENABLE_TSAN=ON
            without_jemalloc: -DDISABLE_JEMALLOC=ON
            with_openssl: -DENABLE_OPENSSL=ON
            compiler: clang
            runtime_env_vars: TSAN_OPTIONS="suppressions=$(realpath ./tests/tsan-suppressions)"
          - name: Ubuntu GCC Ninja
            os: ubuntu-18.04
            with_ninja: --ninja
            with_openssl: -DENABLE_OPENSSL=ON
            compiler: gcc
          - name: Ubuntu GCC Ninja without Jemalloc
            os: ubuntu-18.04
            with_ninja: --ninja
            without_jemalloc: -DDISABLE_JEMALLOC=ON
            with_openssl: -DENABLE_OPENSSL=ON
            compiler: gcc
          - name: Ubuntu GCC without luajit
            os: ubuntu-18.04
            without_luajit: -DUSE_LUAJIT=OFF
            with_openssl: -DENABLE_OPENSSL=ON
            compiler: gcc
          - name: Ubuntu GCC without OpenSSL
            os: ubuntu-18.04
            compiler: gcc

    runs-on: ${{ matrix.os }}
    steps:
      - name: Cache redis
        id: cache-redis
        uses: actions/cache@v2
        with:
          path: |
            ~/local/bin/redis-cli
          key: ${{ runner.os }}-redis-cli

      - name: Setup macOS
        if: ${{ startsWith(matrix.os, 'macos') }}
        run: |
          brew install cmake gcc autoconf automake libtool openssl
          echo "NPROC=$(sysctl -n hw.ncpu)" >> $GITHUB_ENV
          echo "CMAKE_EXTRA_DEFS=-DOPENSSL_ROOT_DIR=/usr/local/opt/openssl" >> $GITHUB_ENV

      - name: Setup Linux
        if: ${{ startsWith(matrix.os, 'ubuntu') }}
        run: |
          sudo apt update
          sudo apt install -y tcl8.5 ninja-build tcl-tls
          echo "NPROC=$(nproc)" >> $GITHUB_ENV

      - name: Install redis
        if: steps.cache-redis.outputs.cache-hit != 'true'
        run: |
          curl -O https://download.redis.io/releases/redis-6.2.6.tar.gz
          tar -xzvf redis-6.2.6.tar.gz
          mkdir -p $HOME/local/bin
          pushd redis-6.2.6 && BUILD_TLS=yes make -j$NPROC redis-cli && mv src/redis-cli $HOME/local/bin/ && popd

      - name: Checkout Code Base
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Build Kvrocks
        run: |
          ./x.py build -j$NPROC --unittest --compiler ${{ matrix.compiler }} ${{ matrix.without_jemalloc }} ${{ matrix.without_luajit }} \
            ${{ matrix.with_ninja }} ${{ matrix.with_sanitizer }} ${{ matrix.with_openssl }} ${{ env.CMAKE_EXTRA_DEFS }}

      - name: Run Unit Test
        run: |
          export ${{ matrix.runtime_env_vars }}
          ./build/unittest

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19.x

      - name: Run Go Integration Cases
        run: |
          export ${{ matrix.runtime_env_vars }}
          ./x.py test go build
          SANITIZER_OUTPUT=$(grep "Sanitizer:" tests/gocase/workspace -r || true)
          if [[ $SANITIZER_OUTPUT ]]; then
            echo "$SANITIZER_OUTPUT"
            echo "\ndetail reports:\n"
            cat $(find tests/gocase/workspace -iname stderr)
            echo "sanitizer error was reported, exiting..."
            exit 1
          fi

      - name: Run Redis Tcl Test
        run: |
          export ${{ matrix.runtime_env_vars }}
          ./x.py test tcl build --cli-path $HOME/local/bin/redis-cli --dont-clean
          if [[ -n "${{ matrix.with_openssl }}" ]] && [[ "${{ matrix.os }}" == ubuntu* ]]; then
            git clone https://github.com/jsha/minica
            cd minica && go build && cd ..
            ./minica/minica --domains localhost
            mkdir -p tests/tcl/tests/tls
            cp localhost/cert.pem tests/tcl/tests/tls/server.crt
            cp localhost/key.pem tests/tcl/tests/tls/server.key
            cp localhost/cert.pem tests/tcl/tests/tls/client.crt
            cp localhost/key.pem tests/tcl/tests/tls/client.key
            cp minica.pem tests/tcl/tests/tls/ca.crt
            ./x.py test tcl build --tls --single unit/tls --dont-clean
          fi
          SANITIZER_OUTPUT=$(grep "Sanitizer:" tests/tcl/tests/tmp -r || true)
          if [[ $SANITIZER_OUTPUT ]]; then
            echo "$SANITIZER_OUTPUT"
            echo "\ndetail reports:\n"
            cat $(find tests/tcl/tests/tmp -iname stderr)
            echo "sanitizer error was reported, exiting..."
            exit 1
          fi

  required:
    if: always()
    name: Required
    runs-on: ubuntu-latest
    needs:
      - build-and-test
    steps:
      - name: Merge requirement checking
        run: |
          build_and_test=${{ needs.build-and-test.result }}

          if [[ $build_and_test != 'success' ]]; then
            exit 1
          fi
